name: build-and-push-to-ghcr
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: '7.1.2'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: scottaubrey/mattermost-team-server
  CURL_IMAGE_NAME: scottaubrey/curl

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push (mattermost)
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: VERSION=${{ inputs.version }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.version }}
      - name: Build and push (curl)
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.curl
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: VERSION=${{ inputs.version }}
          tags: ${{ env.REGISTRY }}/${{ env.CURL_IMAGE_NAME }}:${{ inputs.version }}